### ISSUE TITLE
Serverless Use

### ISSUE THREAD

**Issue by idkjs** [mrmurphy/serbet#4]
Random question. Could this be used in a serverless application? 

This ziet project: https://github.com/zeit/now/tree/master/examples/create-react-app is using `go` code as an endpoint. Wondering if this would be able to used in that context. I don't know enough about http to know if this is dumb question. Apologies in advance.

**Comment by mrmurphy** [comment]
No problem! I haven't done it myself really, but since this just uses Express.js under the hood, it'd theoretically work on any platform that supports using Express in serverless functions. The pain you'll run into is your bundle size. Since there are JS libraries that ship with bs-platform, and JS code compiled with bucklescript relies on those libraries, bs-platform cannot be a dev dependency. And the npm package bundles with it the entire OCaml compiler, which is pretty big. So unless you bundle your code into one JS file before shipping, your code may not even fit into the size requirements for a serverless function. There are a couple of projects that the Zeit folks wrote to make bundling like this easier, and I remember being very impressed by them a couple of years ago when I was researching this, but I haven't actually gone down that path myself.

I hope that's helpful!

**Comment by idkjs** [comment]
That is very informative. Thank you for the detailed answer, sir. Best.
